# Generated by Django 5.1.3 on 2024-11-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='enterprise',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
